# Generated by Django 6.0.6 on 2026-06-23 23:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0002_add_workspace_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("journal", models.TextField(blank=True)),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("great", "😄 Great"),
                            ("good", "🙂 Good"),
                            ("neutral", "😐 Neutral"),
                            ("bad", "😕 Bad"),
                            ("awful", "😣 Awful"),
                        ],
                        max_length=10,
                    ),
                ),
                ("energy", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_entries",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "workspace", "date")},
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("emoji", models.CharField(blank=True, max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("work", "Work"),
                            ("personal", "Personal"),
                            ("health", "Health"),
                            ("learning", "Learning"),
                            ("other", "Other"),
                        ],
                        default="work",
                        max_length=12,
                    ),
                ),
                ("is_done", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "daily_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_blocks",
                        to="planner.dailyentry",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("is_done", models.BooleanField(default=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="planner.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("habit", "date")},
            },
        ),
    ]
