# Generated by Django 6.0.6 on 2026-06-23 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
        ("workspaces", "0002_add_workspace_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("week", models.PositiveSmallIntegerField()),
                ("went_well", models.TextField(blank=True)),
                ("to_improve", models.TextField(blank=True)),
                ("next_focus", models.TextField(blank=True)),
                ("mit1", models.CharField(blank=True, max_length=200)),
                ("mit2", models.CharField(blank=True, max_length=200)),
                ("mit3", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reviews",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-week"],
                "unique_together": {("user", "workspace", "year", "week")},
            },
        ),
    ]
