# Generated by Django 6.0.6 on 2026-06-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_weeklyreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyentry",
            name="emotion_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dailyentry",
            name="gratitude",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dailyentry",
            name="one_liner",
            field=models.TextField(blank=True),
        ),
    ]
