# Generated by Django 6.0.6 on 2026-06-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="acceptance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[("standard", "Standard"), ("research", "Research")],
                default="standard",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="pub_doi",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="publication_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("writing", "Writing"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("revision", "Revision"),
                    ("accepted", "Accepted"),
                    ("published", "Published"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="submission_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="target_journal",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
