# Generated by Django 6.0.6 on 2026-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
    ]
