# Generated by Django 6.0.6 on 2026-06-24 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_add_research_fields"),
        ("tasks", "0005_checklist_startdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("status_changed", "상태 변경"),
                            ("priority_changed", "우선순위 변경"),
                            ("task_created", "태스크 생성"),
                            ("assigned", "담당자 배정"),
                            ("due_date_passed", "마감일 초과"),
                        ],
                        max_length=30,
                    ),
                ),
                ("trigger_val", models.JSONField(blank=True, default=dict)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("change_status", "상태 변경"),
                            ("change_priority", "우선순위 변경"),
                            ("assign_to", "담당자 변경"),
                            ("notify_assignee", "담당자 알림"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action_val", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("action_taken", models.CharField(blank=True, max_length=200)),
                ("success", models.BooleanField(default=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="automation.rule",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_logs",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
    ]
