# Generated by Django 6.0.6 on 2026-06-30 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0002_calendarevent_color"),
        ("workspaces", "0003_savedview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="external_source",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["external_source", "external_id"], name="calendars_c_externa_30f8bb_idx"
            ),
        ),
    ]
