# Generated by Django 6.0.6 on 2026-06-30 04:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_calendarevent_external_id_and_more'),
        ('workspaces', '0003_savedview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTreeIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='TimeTree', max_length=100)),
                ('timetree_email', models.EmailField(max_length=254)),
                ('encrypted_password', models.TextField(blank=True, default='')),
                ('calendar_code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('success', 'Success'), ('error', 'Error')], default='', max_length=10)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetree_integrations', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
