# Generated by Django 6.0.6 on 2026-06-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='sub',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('comment_added', 'Comment Added'), ('mention', 'Mention'), ('status_changed', 'Status Changed'), ('file_attached', 'File Attached'), ('due_soon', 'Due Soon'), ('sprint_started', 'Sprint Started'), ('info', 'Info'), ('system', 'System')], max_length=20),
        ),
    ]
